import type { Merchant } from './types';

/**
 * Commerces de démonstration (données 100 % locales).
 * Servent à valider l'UX avant l'intégration Mapbox + Supabase.
 */
export const DEMO_MERCHANTS: Merchant[] = [
  {
    id: 'm1',
    name: 'La Ferme du Coteau',
    category: 'producer',
    description: 'Maraîcher bio en vente directe, paniers de saison et circuit court.',
    coordinates: { latitude: 45.764, longitude: 4.8357 },
    distanceLabel: '320 m',
    isOpenNow: true,
    isProducer: true,
    isAccessible: true,
    hasRewards: true,
    ecoScore: 94,
    pin: { x: 28, y: 34 },
  },
  {
    id: 'm2',
    name: 'Épicerie Vrac & Co',
    category: 'grocery',
    description: 'Épicerie zéro déchet, produits locaux et consigne réutilisable.',
    coordinates: { latitude: 45.7662, longitude: 4.834 },
    distanceLabel: '540 m',
    isOpenNow: true,
    isProducer: false,
    isAccessible: true,
    hasRewards: true,
    ecoScore: 88,
    pin: { x: 62, y: 26 },
  },
  {
    id: 'm3',
    name: 'Café Solidaire Le Tilleul',
    category: 'restaurant',
    description: 'Cantine locale, produits de saison et prix suspendus solidaires.',
    coordinates: { latitude: 45.7611, longitude: 4.8402 },
    distanceLabel: '780 m',
    isOpenNow: false,
    isProducer: false,
    isAccessible: true,
    hasRewards: false,
    ecoScore: 79,
    pin: { x: 44, y: 58 },
  },
  {
    id: 'm4',
    name: 'Le Rucher Urbain',
    category: 'producer',
    description: 'Apiculteur de quartier, miels et essaims, ateliers pédagogiques.',
    coordinates: { latitude: 45.7588, longitude: 4.8311 },
    distanceLabel: '1,1 km',
    isOpenNow: true,
    isProducer: true,
    isAccessible: false,
    hasRewards: false,
    ecoScore: 91,
    pin: { x: 74, y: 64 },
  },
  {
    id: 'm5',
    name: 'Ressourcerie du Parc',
    category: 'shop',
    description: 'Objets réemployés, réparation et seconde vie des équipements.',
    coordinates: { latitude: 45.7705, longitude: 4.8375 },
    distanceLabel: '1,4 km',
    isOpenNow: false,
    isProducer: false,
    isAccessible: true,
    hasRewards: true,
    ecoScore: 85,
    pin: { x: 18, y: 72 },
  },
  {
    id: 'm6',
    name: 'Atelier Vélo Partagé',
    category: 'service',
    description: 'Auto-réparation de vélos, pièces reconditionnées et entraide.',
    coordinates: { latitude: 45.7639, longitude: 4.8288 },
    distanceLabel: '1,6 km',
    isOpenNow: true,
    isProducer: false,
    isAccessible: true,
    hasRewards: false,
    ecoScore: 82,
    pin: { x: 84, y: 42 },
  },
];
